=== VirgileSarniguet/Bigvir2084_XML_DB_modeling/XMLSchemabigvir84.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://finalassignment.org/XMLbigvir84Schema" elementFormDefault="qualified" xmlns:bv="http://finalassignment.org/XMLbigvir84Schema">
	<xs:element name="BigVir2084_database" type="bv:BigVir2084_databasetype">
		
		<!-- Each medical service ID is a key -->
		<xs:key name="medKey">
				<xs:selector xpath=".//bv:medicalService"/>
				<xs:field xpath="@medSerId"/>
			</xs:key>
		<!-- Each citizen as one or more referent physician which id refer to the medical service key -->
		<xs:keyref name="refphysician" refer="bv:medKey">
				<xs:selector xpath=".//bv:referentPhysician"/>
				<xs:field xpath="@refphysicianId"/>
		</xs:keyref>
	
		<!-- Each citizen ID is a key -->
		<xs:key name="citKey">
				<xs:selector xpath=".//bv:citizen"/>
				<xs:field xpath="@idCitizen"/>
		</xs:key>
		<!-- Each citizen has some social event, in which is included contact with other citizen they had. Thus each contactwith ID refer to a citizen ID -->
		<xs:keyref name="contactWith" refer="bv:citKey">
				<xs:selector xpath=".//bv:contactWithCitId"/>
				<xs:field xpath="@citizenId"/>
		</xs:keyref>	
		
		<!-- Each medical act is executed by a medical service, thus the remefserID attribut reference a medical service id key -->
		<xs:keyref name="refmedSerId" refer="bv:medKey">
			<xs:selector xpath=".//bv:medicalActs/*"/>
			<xs:field xpath="@refMedSerId"/>
		</xs:keyref>

		<!-- Each event ID is a key -->
		<xs:key name="evtKey">
			<xs:selector xpath=".//bv:event"/>
			<xs:field xpath="@eventId"/>
		</xs:key>
		<!-- Citizens can participate to event which eventID refer to the event key-->
		<xs:keyref name="event" refer="bv:evtKey">
			<xs:selector xpath=".//bv:socialEvent"/>
			<xs:field xpath="bv:eventId"/>
		</xs:keyref>
		
		<!-- Each place ID is a key -->
		<xs:key name="plaKey">
			<xs:selector xpath=".//bv:publicPlace"/>
			<xs:field xpath="@publicPlaceId"/>
		</xs:key>
		<!-- Citizens can go to a place which placeID refer to the place key-->
		<xs:keyref name="placeev" refer="bv:plaKey">
			<xs:selector xpath=".//bv:socialEvent"/>
			<xs:field xpath="bv:placeId"/>
		</xs:keyref>
		
	</xs:element>
	<xs:complexType name="BigVir2084_databasetype">
		<xs:sequence>
			<xs:element name="citizens" type="bv:citizensType">
			</xs:element>
			<xs:element name="medicalServices" type="bv:medicalServices">
			</xs:element>
			<xs:element name="events" type="bv:eventsType"/>
			<xs:element name="publicPlaces" type="bv:publicPlacesType"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="citizensType">
		<xs:sequence>
			<xs:element name="citizen" type="bv:citizenType" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="citizenType">
		<xs:sequence>
			<xs:element name="personalInformation" type="bv:personalInformationType"/>
			<xs:element name="medicalInformation" type="bv:medicalInformationType"/>
			<xs:element name="medicalHistory" type="bv:medicalHistoryType"/>
			<xs:element name="socialInformation" type="bv:socialInformationType"/>
		</xs:sequence>
		<xs:attribute name="idCitizen" type="xs:string" use="required"/>
	</xs:complexType>
	
	<xs:complexType name="personalInformationType">
		<xs:sequence>
			<xs:element name="name" type="xs:string"/>
			<xs:element name="surname" type="xs:string"/>
			<xs:element name="dateOfBirth" type="xs:date"/>
			<xs:element name="adress" type="xs:string"/>
			<xs:element name="zipcode">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="[0-9]{5}(-[0-9]{4})?"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:choice>
				<xs:element name="mobilePhoneNumber">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:pattern value="\d{10}"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="fixPhoneNumber">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:pattern value="\d{10}"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
			</xs:choice>
			<xs:element ref="bv:mailAdress"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="medicalInformationType">
		<xs:sequence>
			<xs:element name="sex">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="F"/>
						<xs:enumeration value="M"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="weightKg" type="xs:positiveInteger"/>
			<xs:element name="heightCm" type="xs:decimal"/>
			<xs:element name="age" type="xs:positiveInteger"/>
			<xs:element name="medications" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="medication" minOccurs="0" maxOccurs="unbounded">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="drugName" type="xs:string"/>
								<xs:element name="dailyDosage" type="xs:string"/>
								<xs:element name="startDate" type="xs:date"/>		
							</xs:sequence>
						</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="referentPhysicians">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="referentPhysician" minOccurs="1" maxOccurs="unbounded"><!--A Citizen must have at least a general practitioner referent-->
							<xs:complexType>
								<xs:attribute name="refphysicianId" type="xs:string" use="required"/>
								<xs:attribute name="speciality" type="xs:string" use="required"/>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="Allergies" minOccurs="0" maxOccurs="1">
				<xs:simpleType>
					<xs:list itemType="xs:string"/>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="medicalHistoryType">
		<xs:all>
			<xs:element name="medicalActs" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="consultation" minOccurs="0" maxOccurs="unbounded">
							<xs:complexType>	
								<xs:complexContent>
									<xs:extension base="bv:act">
										<xs:sequence>
											<xs:element name="consultationResult" type="xs:string"/>
											<xs:element name="prescription" type="xs:string" minOccurs="0"/>
										</xs:sequence>
									</xs:extension>
								</xs:complexContent>
							</xs:complexType>
						</xs:element>
						<xs:element name="laboratoryTest" minOccurs="0" maxOccurs="unbounded">
							<xs:complexType>
								<xs:complexContent>
									<xs:extension base="bv:act">
										<xs:sequence>
											<xs:element name="pathologieTested" type="xs:string"/>
											<xs:element name="testResult" type="xs:boolean" minOccurs="0"/>
											<xs:element name="resultDetails" type="xs:string" minOccurs="0"/>
										</xs:sequence>
									</xs:extension>
								</xs:complexContent>
							</xs:complexType>
						</xs:element>
						<xs:element name="surgery" minOccurs="0" maxOccurs="unbounded">
							<xs:complexType>
								<xs:complexContent>
									<xs:extension base="bv:act">
										<xs:sequence>
											<xs:element name="interventionDescription" type="xs:string"/>
										</xs:sequence>
									</xs:extension>
								</xs:complexContent>
							</xs:complexType>
						</xs:element>
						<xs:element name="hospitalisation" minOccurs="0" maxOccurs="unbounded">
							<xs:complexType>
								<xs:complexContent>
									<xs:extension base="bv:act">
										<xs:sequence>
											<xs:element name="reason" type="xs:string"/>
											<xs:element name="lengthInDays" type="xs:nonNegativeInteger"/>
										</xs:sequence>
									</xs:extension>
								</xs:complexContent>
							</xs:complexType>
						</xs:element>
					</xs:sequence>	
				</xs:complexType>				
			</xs:element>
			<xs:element name="infections" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
					   <xs:element name="infection" maxOccurs="unbounded">
						   <xs:complexType>
							   <xs:attribute name="pathologie" type="xs:string"/>
							   <xs:attribute name="date" type="xs:date"/>		
						   </xs:complexType>
					   </xs:element>
					</xs:sequence>
				</xs:complexType>	
			</xs:element>
			<xs:element name="vaccinationStatutes">
				 <xs:complexType>
					<xs:sequence>
					   <xs:element name="vaccin" minOccurs="0" maxOccurs="unbounded">
						   <xs:complexType>
							   <xs:all>
								  <xs:element name="pathologie" type="xs:string"/>	
						          <xs:element name="upToDate" type="xs:boolean"/>
							   </xs:all>
							   <xs:attribute name="date" type="xs:date"/>
						   </xs:complexType>
					   </xs:element>
					</xs:sequence>
				</xs:complexType>	
			</xs:element>
			<xs:element name="immunizationStatus" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
					   <xs:element name="pathologie" minOccurs="0" maxOccurs="unbounded">
						   <xs:complexType>
							   <xs:all>
								  <xs:element name="name" type="xs:string"/>	
						          <xs:element name="result" type="xs:string"/>
							   </xs:all>
							   <xs:attribute name="testDate" type="xs:date"/>
						   </xs:complexType>
					   </xs:element>
					</xs:sequence>
				</xs:complexType>		
			</xs:element>	
		</xs:all>
	</xs:complexType>
	
	<!-- Creation of the complextype act, which will be used as a basis for different extensions for all the different kind of medical acts -->
	<xs:complexType name="act">
		<xs:sequence>
			<xs:element name="generalComments" type="xs:string" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
		<xs:attribute name="date" type="xs:date"/>
		<xs:attribute name="refMedSerId" type="xs:string"/>
	</xs:complexType>
	
	
	<xs:complexType name="socialInformationType">
		<xs:all>
			<xs:element name="socialRelations" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="contactWithCitId" minOccurs="0" maxOccurs="unbounded">
							<xs:complexType>
								<xs:sequence>
									<xs:element ref="bv:locationAdress" minOccurs="0"/>
								</xs:sequence>
								<xs:attribute name="date" type="xs:date" use="required"/>
								<xs:attribute name="citizenId" type="xs:string" use="required"/>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="socialHistory" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="socialEvent" minOccurs="0" maxOccurs="unbounded"><!--It could be a participation to an event or being in a public place-->
							<xs:complexType>
								<xs:sequence>
									<xs:element name="placeOrEventName" type="xs:string"/>
									<xs:choice>
										 <xs:element name="eventId" type="xs:string"/>
										 <xs:element name="placeId" type="xs:string"/>
									</xs:choice>
								</xs:sequence>
								<xs:attribute name="date" type="xs:date"/>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:all>		
	</xs:complexType>
	
	<xs:complexType name="medicalServices">
		<xs:sequence>
			<xs:element name="medicalService" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="name" type="xs:string"/>
						<xs:element name="surname" type="xs:string" minOccurs="0"/>
						<xs:element name="adress" type="xs:string"/>
						<xs:element name="type">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="hospital"/>
									<xs:enumeration value="physician"/>
									<xs:enumeration value="medical laboratory"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:element>
						<xs:element name="speciality" type="xs:string" minOccurs="0"/>
						<xs:element name="phoneNumber">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:pattern value="\d{10}"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:element>
						<xs:element ref="bv:mailAdress"/>
					</xs:sequence>
					<xs:attribute name="medSerId" type="xs:string" use="required"/>
				</xs:complexType>
			</xs:element>	
		</xs:sequence>			
	</xs:complexType>
	
	<xs:complexType name="eventsType">
		<xs:sequence>
			<xs:element name="event" maxOccurs="unbounded">
				<xs:complexType>
					<xs:all>
						<xs:element name="name" type="xs:string"/>
						<xs:element name="date" type="xs:date"/>
						<xs:element name="endDate" type="xs:date"/>
						<xs:element name="type" type="xs:string"/>
						<xs:element ref="bv:locationAdress"/>
					</xs:all>
					<xs:attribute name="eventId" type="xs:string" use="required"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="publicPlacesType">
		<xs:sequence>
			<xs:element name="publicPlace" maxOccurs="unbounded">
				<xs:complexType>
					<xs:all>
						<xs:element name="name" type="xs:string"/>
						<xs:element name="type" type="xs:string"/>
						<xs:element ref="bv:locationAdress"/>
					</xs:all>
					<xs:attribute name="publicPlaceId" type="xs:string" use="required"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>	
	</xs:complexType>
	
	<!-- Creation of the element location adress which will be use several times in different part of the schema -->
	<xs:element name="locationAdress">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="longitude" type="xs:float"/>
					<xs:attribute name="latitude" type="xs:float"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	
	<!-- Creation of the element location adress which will be use several times in different part of the schema -->
	<xs:element name="mailAdress">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="[_\-a-zA-Z0-9\.\+]+@[a-zA-Z0-9](\.?[\-a-zA-Z0-9]*[a-zA-Z0-9])*"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>

</xs:schema>

=== VirgileSarniguet/Bigvir2084_XML_DB_modeling/XMLbigvir84db.xml
<?xml version="1.0" encoding="utf-8"?>
<bv:BigVir2084_database xmlns:bv="http://finalassignment.org/XMLbigvir84Schema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://finalassignment.org/XMLbigvir84Schema XMLSchemabigvir84.xsd">
	<bv:citizens>
		<bv:citizen idCitizen="cit001">
			<bv:personalInformation>
				<bv:name>Samuel</bv:name>
				<bv:surname>Bricot</bv:surname>
				<bv:dateOfBirth>1992-09-12</bv:dateOfBirth>
				<bv:adress>45 rue de la chipo, Le Rheu</bv:adress>
				<bv:zipcode>35650</bv:zipcode>
				<bv:mobilePhoneNumber>0618599098</bv:mobilePhoneNumber>
				<bv:mailAdress>samuel@laposte.net</bv:mailAdress>
			</bv:personalInformation>
			<bv:medicalInformation>
				<bv:sex>M</bv:sex>
				<bv:weightKg>67</bv:weightKg>
				<bv:heightCm>187</bv:heightCm>
				<bv:age>28</bv:age>
				<bv:referentPhysicians>
					<bv:referentPhysician refphysicianId="phy002" speciality="general practitioner"/>
				</bv:referentPhysicians>
				<bv:Allergies>Pollen Fruits Acariens</bv:Allergies>	
			</bv:medicalInformation>
			<bv:medicalHistory>
				<bv:medicalActs>
					<bv:consultation date="2021-06-08" refMedSerId="phy001">
						<bv:consultationResult>Patient present bigvir84 symptomas</bv:consultationResult>
						<bv:prescription>bigvir84 medical test</bv:prescription>
					</bv:consultation>
					<bv:laboratoryTest date="2021-06-09" refMedSerId="lab003">
						<bv:pathologieTested>bigvir84</bv:pathologieTested>
						<bv:testResult>1</bv:testResult>
						<bv:resultDetails>Patient positive to bigvir84 with viral load of 0.6</bv:resultDetails>
					</bv:laboratoryTest>
				</bv:medicalActs>
				<bv:infections>
					<bv:infection pathologie="Tuberculoses" date="2012-07-14"/>		
				</bv:infections>
				<bv:vaccinationStatutes>
					<bv:vaccin date="2006-09-18">
						<bv:pathologie>thetanos</bv:pathologie>
						<bv:upToDate>1</bv:upToDate>
					</bv:vaccin>
					<bv:vaccin date="2002-06-07">
						<bv:pathologie>hepatite A</bv:pathologie>
						<bv:upToDate>1</bv:upToDate>
					</bv:vaccin>	
				</bv:vaccinationStatutes>
			</bv:medicalHistory>
			<bv:socialInformation>
				<bv:socialRelations>
					<bv:contactWithCitId date="2021-06-10" citizenId="cit005">
						<bv:locationAdress latitude="48.111598" longitude="-1.685317">32 rue du chapito Rennes 35000</bv:locationAdress>
					</bv:contactWithCitId>
					<bv:contactWithCitId date="2021-06-10" citizenId="cit003">
					</bv:contactWithCitId>	
				</bv:socialRelations>
				<bv:socialHistory>
					<bv:socialEvent date="2021-06-07">
						<bv:placeOrEventName> Mall Bougaloo </bv:placeOrEventName>
						<bv:placeId>pla002</bv:placeId>
					</bv:socialEvent>
					<bv:socialEvent date="2021-06-07">
						<bv:placeOrEventName> Restaurant des 3 chips </bv:placeOrEventName>
						<bv:placeId>pla001</bv:placeId>
					</bv:socialEvent>
					<bv:socialEvent date="2021-06-04">
						<bv:placeOrEventName> Festival des vieilles charrues</bv:placeOrEventName>
						<bv:eventId>evt001</bv:eventId>
					</bv:socialEvent>
				</bv:socialHistory>
			</bv:socialInformation>
		</bv:citizen>
		
		<bv:citizen idCitizen="cit002">
			<bv:personalInformation>
				<bv:name>Marcelus</bv:name>
				<bv:surname>Conpito</bv:surname>
				<bv:dateOfBirth>1954-02-12</bv:dateOfBirth>
				<bv:adress>3 rue du pistolet, Tours </bv:adress>
				<bv:zipcode>37000</bv:zipcode>
				<bv:fixPhoneNumber>0299641387</bv:fixPhoneNumber>
				<bv:mailAdress>marcelolerigolo@google.net</bv:mailAdress>
			</bv:personalInformation>
			<bv:medicalInformation>
				<bv:sex>M</bv:sex>
				<bv:weightKg>62</bv:weightKg>
				<bv:heightCm>167</bv:heightCm>
				<bv:age>67</bv:age>
				<bv:referentPhysicians>
					<bv:referentPhysician refphysicianId="phy001" speciality="general practitioner"/>
					<bv:referentPhysician refphysicianId="phy005" speciality="cardiologist"/>
				</bv:referentPhysicians>
				<bv:Allergies>Peanut</bv:Allergies>
			</bv:medicalInformation>
			<bv:medicalHistory>
				<bv:medicalActs>
					<bv:consultation date="2021-06-03" refMedSerId="phy001">
						<bv:consultationResult>Patient present bigvir84 symptomas</bv:consultationResult>
						<bv:prescription>bigvir84 medical test</bv:prescription>
					</bv:consultation>
					<bv:laboratoryTest date="2015-03-04" refMedSerId="lab003">
						<bv:pathologieTested>HIV</bv:pathologieTested>
						<bv:testResult>0</bv:testResult>
					</bv:laboratoryTest>
					<bv:laboratoryTest date="2021-06-04" refMedSerId="lab003">
						<bv:pathologieTested>bigvir84</bv:pathologieTested>
						<bv:testResult>1</bv:testResult>
						<bv:resultDetails>Patient positive to bigvir84 with viral load of 0.2</bv:resultDetails>
					</bv:laboratoryTest>
					<bv:surgery date="2012-06-15" refMedSerId="phy005">
						<bv:interventionDescription>Hearth replacement surgery</bv:interventionDescription>
					</bv:surgery>
				</bv:medicalActs>
				<bv:infections>
					<bv:infection pathologie="malaria" date="2014-06-14"/>
				</bv:infections>
				<bv:immunizationStatus>
					<bv:pathologie testDate="2015-06-19">
						<bv:name>H1N1 flu</bv:name>
						<bv:result>negatif</bv:result>
					</bv:pathologie>
					<bv:pathologie testDate="2021-04-15">
						<bv:name>bigvir84</bv:name>
						<bv:result>negatif</bv:result>
					</bv:pathologie>
				</bv:immunizationStatus>
				<bv:vaccinationStatutes>
					<bv:vaccin date="2006-09-18">
						<bv:pathologie>thetanos</bv:pathologie>
						<bv:upToDate>1</bv:upToDate>
					</bv:vaccin>
					<bv:vaccin date="2002-06-07">
						<bv:pathologie>hepatite A</bv:pathologie>
						<bv:upToDate>1</bv:upToDate>
					</bv:vaccin>
				</bv:vaccinationStatutes>
			</bv:medicalHistory>
			<bv:socialInformation>
				<bv:socialRelations>
					<bv:contactWithCitId date="2021-06-09" citizenId="cit004">
						<bv:locationAdress latitude="48.111591" longitude="-1.685311">32 rue du champ jacquet Rennes 35000</bv:locationAdress>
					</bv:contactWithCitId>
					<bv:contactWithCitId date="2021-06-08" citizenId="cit002">
					</bv:contactWithCitId>
				</bv:socialRelations>
				<bv:socialHistory>
					<bv:socialEvent date="2021-06-02">
						<bv:placeOrEventName> Musee des beaux arts </bv:placeOrEventName>
						<bv:placeId>pla003</bv:placeId>
					</bv:socialEvent>
					<bv:socialEvent date="2021-06-07">
						<bv:placeOrEventName> Cinema CGR </bv:placeOrEventName>
						<bv:placeId>pla004</bv:placeId>
					</bv:socialEvent>
					<bv:socialEvent date="2021-06-09">
						<bv:placeOrEventName> Rolland Garos </bv:placeOrEventName>
						<bv:eventId>evt005</bv:eventId>
					</bv:socialEvent>
				</bv:socialHistory>
			</bv:socialInformation>
		</bv:citizen>
		
		<bv:citizen idCitizen="cit003">
			<bv:personalInformation>
				<bv:name>Josianne</bv:name>
				<bv:surname>Garibaldi</bv:surname>
				<bv:dateOfBirth>1948-01-12</bv:dateOfBirth>
				<bv:adress>35 rue du pipo, Paris</bv:adress>
				<bv:zipcode>75013</bv:zipcode>
				<bv:fixPhoneNumber>0299641387</bv:fixPhoneNumber>
				<bv:mailAdress>josijozee@gmail.net</bv:mailAdress>
			</bv:personalInformation>
			<bv:medicalInformation>
				<bv:sex>F</bv:sex>
				<bv:weightKg>52</bv:weightKg>
				<bv:heightCm>163</bv:heightCm>
				<bv:age>73</bv:age>
				<bv:medications>
					<bv:medication>
						<bv:drugName>buronzan</bv:drugName>
						<bv:dailyDosage>125 mg</bv:dailyDosage>
						<bv:startDate>2019-05-01</bv:startDate>
					</bv:medication>
					<bv:medication>
						<bv:drugName>maxipropulsator</bv:drugName>
						<bv:dailyDosage>1300 mg</bv:dailyDosage>
						<bv:startDate>2018-02-28</bv:startDate>
					</bv:medication>
				</bv:medications>
				<bv:referentPhysicians>
					<bv:referentPhysician refphysicianId="phy002" speciality="general practitioner"/>
					<bv:referentPhysician refphysicianId="phy006" speciality="pulmonologist"/>
				</bv:referentPhysicians>
			</bv:medicalInformation>
			<bv:medicalHistory>
				<bv:medicalActs>
					<bv:consultation date="2020-06-03" refMedSerId="phy002">
						<bv:consultationResult>Patient has the flue</bv:consultationResult>
						<bv:prescription>sleep/soup and ibuprofène</bv:prescription>
					</bv:consultation>
					<bv:laboratoryTest date="2016-03-04" refMedSerId="lab003">
						<bv:pathologieTested>Syphilis</bv:pathologieTested>
						<bv:testResult>0</bv:testResult>
					</bv:laboratoryTest>
					<bv:laboratoryTest date="2021-06-10" refMedSerId="lab002">
						<bv:pathologieTested>bigvir84</bv:pathologieTested>
						<bv:testResult>1</bv:testResult>
						<bv:resultDetails>Patient positive to bigvir84 with viral load of 0.5</bv:resultDetails>
					</bv:laboratoryTest>
					<bv:surgery date="2012-06-15" refMedSerId="phy007">
						<bv:interventionDescription>brain implant</bv:interventionDescription>
					</bv:surgery>
					<bv:hospitalisation date="2012-06-14" refMedSerId="hosp001">
						<bv:reason>brain surgery</bv:reason>
						<bv:lengthInDays>15</bv:lengthInDays>
					</bv:hospitalisation>
				</bv:medicalActs>
				<bv:vaccinationStatutes>
					<bv:vaccin date="2003-05-18">
						<bv:pathologie>thetanos</bv:pathologie>
						<bv:upToDate>1</bv:upToDate>
					</bv:vaccin>
					<bv:vaccin date="2001-06-07">
						<bv:pathologie>hepatite A</bv:pathologie>
						<bv:upToDate>0</bv:upToDate>
					</bv:vaccin>
					<bv:vaccin date="2021-05-07">
						<bv:pathologie>bigvir84</bv:pathologie>
						<bv:upToDate>1</bv:upToDate>
					</bv:vaccin>
				</bv:vaccinationStatutes>
			</bv:medicalHistory>
			<bv:socialInformation>
				<bv:socialRelations>
					<bv:contactWithCitId date="2021-06-09" citizenId="cit002">
						<bv:locationAdress latitude="48.1135463" longitude="1.6855455">45 rue de la pompe, 75002, Paris, France</bv:locationAdress>
					</bv:contactWithCitId>
